bayes_optimization:
  init_points: 10   # initial random evaluations
  n_iter: 40       # additional optimization steps

models:
  cgcnn:
    enabled: true
    bounds:
      epochs: [50, 200]
      batch_size: [16, 64]
      lr: [0.0001, 0.005]
      hidden_channels: [32, 128]
      num_layers: [2, 6]
      dropout: [0.0, 0.5]
      weight_decay: [1.0e-6, 1.0e-3]

  megnet:
    enabled: true
    bounds:
      epochs: [50, 200]
      batch_size: [16, 64]
      lr: [0.0001, 0.005]
      hidden_channels: [32, 128]
      num_layers: [2, 6]
      dropout: [0.0, 0.5]
      weight_decay: [1.0e-6, 1.0e-3]

  schnet:
    enabled: true
    bounds:
      epochs: [50, 200]
      batch_size: [16, 64]
      lr: [0.0001, 0.005]
      hidden_channels: [32, 128]
      num_interactions: [2, 6]
      dropout: [0.0, 0.5]
      weight_decay: [1.0e-6, 1.0e-3]

  mpnn:
    enabled: true
    bounds:
      epochs: [50, 200]
      batch_size: [16, 64]
      lr: [0.0001, 0.005]
      hidden_channels: [32, 128]
      num_layers: [2, 6]
      dropout: [0.0, 0.5]
      weight_decay: [1.0e-6, 1.0e-3]

